name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 5.0.0
homepage: https://github.com/justkawal/excel
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ">=3.8.1"
  flutter: ">=3.32.5"

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  equatable: ^2.0.7
  path: any
  web: ^1.1.1
  xml: ^6.6.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  test: ^1.26.3
